# Generated by Django 4.1.3 on 2022-11-15 13:35

from django.db import migrations, models
import factures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('id_facture', models.CharField(max_length=20)),
                ('id_magasin', models.CharField(max_length=20)),
                ('id_client', models.CharField(max_length=20)),
                ('t_vendu', models.CharField(max_length=15)),
                ('t_retour', models.CharField(max_length=15)),
                ('total', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=factures.models.upload_to)),
                ('id_facture', models.CharField(max_length=20)),
                ('id_magasin', models.CharField(max_length=20)),
                ('id_client', models.CharField(max_length=20)),
                ('t_vendu', models.CharField(max_length=15)),
                ('t_retour', models.CharField(max_length=15)),
                ('total', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
